### ISSUE TITLE
Hard coded Paths

### ISSUE THREAD

**Issue by Sabryr** [dib-lab/dib-MMETSP#1]
bash-4.1$ python main.py
Directory created: /work/databases/bio/mmetsp_new/mmetsp/
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import getdata as data
  File "/work/databases/bio/mmetsp_new/dib-MMETSP/getdata.py", line 149, in <module>
    for datafile in datafiles:
NameError: name 'datafiles' is not defined

**Comment by Sabryr** [comment]
Some more hardcoded paths leading to errors:
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import trim_qc as trim
  File "/work/databases/bio/mmetsp_new/dib-MMETSP/trim_qc.py", line 190, in <module>
    execute(url_data,datadir)
  File "/work/databases/bio/mmetsp_new/dib-MMETSP/trim_qc.py", line 168, in execute
    clusterfunc.check_dir(trimdir)
  File "/work/databases/bio/mmetsp_new/dib-MMETSP/clusterfunc.py", line 12, in check_dir
    os.mkdir(dirname)
OSError: [Errno 2] No such file or directory: '/mnt/scratch/ljcohen/mmetsp/Fragilariopsis_kerguelensis/SRR1296820/trim/'

Due to:
def fix_fasta(trinity_fasta, trinity_dir, sample):
    os.chdir(trinity_dir)
    trinity_out = trinity_dir + sample + ".Trinity.fixed.fasta"
    fix = """
sed 's_|_-_g' {} > {}
""".format(trinity_fasta, trinity_out)
    s = subprocess.Popen(fix, shell=True) 
    print fix
    s.wait()
    os.chdir("/mnt/home/ljcohen/MMETSP/")
    return trinity_out

**Comment by Sabryr** [comment]
bash-4.1$ grep -Rni "/mnt/scratch/ljcohen/mmetsp/"
assembly_trinity_20140413p1.py:173:basedir = "/mnt/scratch/ljcohen/mmetsp/"
diginorm_mmetsp.py:183:basedir = "/mnt/scratch/ljcohen/mmetsp/"
trim_qc.py:187:datadir="/mnt/scratch/ljcohen/mmetsp/"
Binary file trim_qc.pyc matches

**Comment by Sabryr** [comment]
More hardcoded paths

java -jar /mnt/home/ljcohen/bin/Trimmomatic-0.33/trimmomatic-0.33.jar PE \\
ILLUMINACLIP:/mnt/home/ljcohen/bin/Trimmomatic-0.33/adapters/combined.fa:2:40:15 \\
java -jar /mnt/home/ljcohen/bin/Trimmomatic-0.33/trimmomatic-0.33.jar PE \\
ILLUMINACLIP:/mnt/home/ljcohen/bin/Trimmomatic-0.33/adapters/combined.fa:2:40:15 \\
datadir="/mnt/scratch/ljcohen/mmetsp/"
